//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class userprofile
    {
        public string userid { get; set; }
        public string imagecontainerid { get; set; }
    }
}
